/*
 * Copyright (c) 2018 Telinc1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
 * OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.telinc1.faerie.gui.main.dialog;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.telinc1.faerie.Resources;
import com.telinc1.faerie.gui.JPaletteView;
import com.telinc1.faerie.gui.main.MainWindow;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import java.awt.Dimension;
import java.awt.Insets;
import java.net.URL;

/**
 * The dialog which is displayed from the main window to show the loaded
 * palette.
 *
 * @author Telinc1
 * @since 1.0.0
 */
public class PaletteDialog extends JDialog {
    /**
     * The {@code MainWindow} to which this {@code PaletteDialog} belongs.
     */
    private MainWindow window;

    private JPanel contentPanel;
    private JPaletteView paletteView;

    /**
     * Construct a Palette dialog, including all of its inner components.
     * <p>
     * The title and sizes are automatically set. Note that the window is not
     * opened.
     */
    public PaletteDialog(MainWindow window){
        super(window, Resources.getString("palette", "title"), true);
        this.window = window;

        this.$$$setupUI$$$();

        this.setContentPane(this.contentPanel);

        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);

        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        URL iconURL = Resources.class.getResource(Resources.PACKAGE + "/images/application.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$(){
        createUIComponents();
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(paletteView, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(256, 256), new Dimension(256, 256), new Dimension(256, 256), 0, false));
    }

    private void createUIComponents(){
        this.paletteView = new JPaletteView();
        this.paletteView
            .setPalette(this.getWindow().getApplication().getPalette())
            .setCellSize(16, 16)
            .setFirstIndex(0x0)
            .setRegionSize(16, 16);
    }

    /**
     * Returns the {@code MainWindow} to which this {@code AboutDialog} belongs.
     */
    public MainWindow getWindow(){
        return this.window;
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$(){ return contentPanel; }
}
